### PR TITLE
palette effect overflow fix

### LINKED ISSUE #4425: Palette effect will not spread palette colors across entire strip
### What happened?

If the strip (or segment) pixel count is larger than 256 pixels, the effect will spread colors only across 256 pixels and then repeat, instead of spreading colors across entire strip (or segment) length.

### To Reproduce Bug

Create a strip (or segment) with more than 256 pixels (preferably more than 384 to pronounce the effect) and select Palette effect.
You will see a sharp color transition at pixel 256.

### Expected Behavior

Spread palette colors across entire strip (or segment) even if pixel count is larger than 256 pixels.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.15.0

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

_No response_

### Anything else?

The bug was introduced with #3683 ~~when using `SEGMENT.color_wheel()` which only takes 256 values instead of `SEGEMENT.color_from_palette()`~~.
cc @TripleWhy  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TripleWhy**
I belive this fixes #4425

### CODE REVIEW

**Comment by TripleWhy** [comment]
Note: this does replace some more 32 bit multiplications with slightly more expensive 64 bit multiplications.

**Comment by blazoncek** [comment]
Tested and works.

File: wled00/FX.cpp [hunk 1]
```diff
@@ -2032,7 +2032,7 @@ uint16_t mode_palette() {
       const mathType sourceX = xtSinTheta + ytCosTheta + centerX;
       // The computation was scaled just right so that the result should always be in range [0, maxXOut], but enforce this anyway
       // to account for imprecision. Then scale it so that the range is [0, 255], which we can use with the palette.
-      int colorIndex = (std::min(std::max(sourceX, mathType(0)), maxXOut * sInt16Scale) * 255) / (sInt16Scale * maxXOut);
+      int colorIndex = (std::min(std::max(sourceX, mathType(0)), maxXOut * sInt16Scale) * wideMathType(255)) / (sInt16Scale * maxXOut);
```
Comment (softhack007) [inline wled00/FX.cpp:2035]: What does `wideMathType()` do? 

Essentially this PR changes "255" to "wideMathType(255)", I'm wondering is this the same as writing "255.0f" or maybe "255UL" ?

Comment (blazoncek) [reply wled00/FX.cpp:2035]: 255ULL for ESP8266 and 255.0f otherwise

Comment (softhack007) [reply wled00/FX.cpp:2035]: Looks like someone tried to avoid fixed point math?

Comment (DedeHai) [reply wled00/FX.cpp:2035]: the way it is implemented is quite an elegant way to support float AND fixed point math.

**Review by DedeHai — APPROVED** [review]
simple fix, approved.
