### PR TITLE
fix timing issue when changing 1D <-> 2D credits to blazoncek

### LINKED ISSUE #4911: Saving 2D config with higher LED count than configured leads to crash
### What happened?

I think this was discussed on Discord. When enabling 2D before setting the right amount of LEDs in config WLED just crashes.
I did some investigation on this but was not able to find where exactly this happes

### To Reproduce Bug

Enable 2D and set the panel size larger than the number of configured LEDs.

### Expected Behavior

Save the 2D setting without crashing.

### Install Method

Self-Compiled

### What version of WLED?

0.16

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Relevant log/trace output

```shell

```

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by DedeHai**
this fixes #4911 and #4800

## Release Notes

* **Bug Fixes**
  * Enhanced synchronization during LED matrix geometry reconfiguration to prevent race conditions
  * Improved stability of LED effect drawing during matrix setup and configuration changes

### CODE REVIEW

File: wled00/set.cpp [hunk 1]
```diff
@@ -815,8 +815,13 @@ void handleSettingsSet(AsyncWebServerRequest *request, byte subPage)
       }
     }
     strip.panel.shrink_to_fit();  // release unused memory
+    // we are changing matrix/ledmap geometry which *will* affect existing segments
+    // since we are not in loop() context we must make sure that effects are not running. credit @blazonchek for properly fixing #4911
+    strip.suspend();
```
Comment (softhack007) [inline wled00/set.cpp:820]: makes sense - we basically have the same logic in WLED-MM for more than a year, and it seems to work well.
