### PR TITLE
Segment fixes

### LINKED ISSUE #4800: 0.16 crashes when changing from 1D stip to 2D Matrix and clicking on save. 0.15 seams fine
### What happened?

Crashes when changing from 1D to 2D and click on save

### To Reproduce Bug

1. Fresh install the latest beta 0.16.
2. Open settings -> 2D Configuration -> Strip or panel: change to 2D Matrix -> Click: Save

```
The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.```

### Expected Behavior

To save the settings

### Install Method

Binary from WLED.me

### What version of WLED?

0.16

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
Backtrace: 0x4008ab44:0x3ffe11f0 0x4008aea1:0x3ffe1210 0x401c0557:0x3ffe1230 0x401680e3:0x3ffe1260 0x4013c1b4:0x3ffe1280 0x40118ba5:0x3ffe12a0 0x4013c7c6:0x3ffe1320 0x4013c827:0x3ffe13b0 0x4008c92a:0x3ffe13e0
  #0  0x4008ab44:0x3ffe11f0 in invoke_abort at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:648
  #1  0x4008aea1:0x3ffe1210 in vApplicationStackOverflowHook at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:648    
  #2  0x401c0557:0x3ffe1230 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<WiFiClientRxBuffer*>(WiFiClientRxBuffer*) at C:\Users\DesktopTV\.platformio\packages\framework-arduinoespressif32\libraries\WiFi\src/WiFiClient.cpp:572
      (inlined by) std::__shared_ptr<WiFiClientRxBuffer, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<WiFiClientRxBuffer>(WiFiClientRxBuffer*) at c:\users\desktoptv\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\bits/shared_ptr_base.h:882
      (inlined by) void std::__shared_ptr<WiFiClientRxBuffer, (__gnu_cxx::_Lock_policy)2>::reset<WiFiClientRxBuffer>(WiFiClientRxBuffer*) at c:\users\desktoptv\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\bits/shared_ptr_base.h:1030
  #3  0x401680e3:0x3ffe1260 in tcp_trigger_input_pcb_close at ??:?
  #4  0x4013c1b4:0x3ffe1280 in DNSServer::replyWithIP() at C:\Users\DesktopTV\.platformio\packages\framework-arduinoespressif32\libraries\DNSServer\src/DNSServer.cpp:189
  #5  0x40118ba5:0x3ffe12a0 in EspalexaDevice::getRGB() at wled00/src/dependencies/espalexa/EspalexaDevice.cpp:312
  #6  0x4013c7c6:0x3ffe1320 in AsyncUDP::listenMulticast(ip_addr const*, unsigned short, unsigned char, tcpip_adapter_if_t) at C:\Users\DesktopTV\.platformio\packages\framework-arduinoespressif32\libraries\AsyncUDP\src/AsyncUDP.cpp:411
  #7  0x4013c827:0x3ffe13b0 in AsyncUDP::listenMulticast(ip_addr const*, unsigned short, unsigned char, tcpip_adapter_if_t) at C:\Users\DesktopTV\.platformio\packages\framework-arduinoespressif32\libraries\AsyncUDP\src/AsyncUDP.cpp:411
  #8  0x4008c92a:0x3ffe13e0 in vPortTaskWrapper at /home/cschwinne/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
```

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by DedeHai**
- pulling in changes from @blazoncek dev branch https://github.com/blazoncek/WLED/tree/dev
- added (and removed again, see comment below) a fix that could potentially lead to crashes (it does NOT fix https://github.com/wled/WLED/issues/4800)

there is another discrepancy in the gap table allocation in `setUpMatrix()`: 
if the gap file has fewer entries than the matrix size, that also may lead to out of bounds access but I was not sure what the proper way to fix it is: ignore the file if it does not match size or just fill it with "1"?

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved memory management and error handling to enhance stability and prevent resource leaks.
  * Enhanced transition handling for LED segments, leading to smoother and more reliable visual effects.
  * Fixed issues related to pixel buffer allocation and deallocation.

* **Other Improvements**
  * Unified and clarified debug output for easier troubleshooting.
  * Refined logic for segment transitions, especially when segment names change.

### CODE REVIEW

File: wled00/FX_2Dfcn.cpp [hunk 1]
```diff
@@ -49,16 +49,14 @@ void WS2812FX::setUpMatrix() {
     suspend();
     waitForIt();
 
-    customMappingSize = 0; // prevent use of mapping if anything goes wrong
+    uint16_t matrixSize = Segment::maxWidth * Segment::maxHeight;
+    customMappingSize = max(getLengthTotal(), matrixSize); // is reset to 0 in case of error
```
Comment (blazoncek) [inline wled00/FX_2Dfcn.cpp]: getLengthTotal() does that.
I don't think it is wise what you did here.

Comment (DedeHai) [reply wled00/FX_2Dfcn.cpp]: you are totally right. will revert.

**Comment by DedeHai** [comment]
is there any other changes / fixes that I missed or is this good to merge?

**Comment by blazoncek** [comment]
I don't see anything particularly wrong but you have to be careful and do extensive testing when pulling from my fork.

It might be good to consolidate DEBUG statements (I use differentiating DEBUG statements, i.e. DEBUGFX_... for effect debugging whereas upstream does not).

**Comment by DedeHai** [comment]
I am running these changes and so far it looks good, but will review the changes again.
`DEBUGFX_PRINT` is in upstream.

**Comment by Andro-Marian** [comment]
Still crashes.
[ESP32 Error.txt](https://github.com/user-attachments/files/21673252/ESP32.Error.txt)
[ESP32 Error 2 After Restart from 1D then changed back to 2D.txt](https://github.com/user-attachments/files/21673328/ESP32.Error.2.After.Restart.from.1D.then.changed.back.to.2D.txt)

**Comment by DedeHai** [comment]
my opening "statement" sais it wont fix it.
