### PR TITLE
Fix array overflow in exploding_fireworks

### LINKED ISSUE #4120: Crashes when leds length is 3
### What happened?

WLed crashes when setting some effects like Fireworks 1D

### To Reproduce Bug

1. Set the Length of leds to 3
2. Set the effect to Fireworks 1D

### Expected Behavior

To work fine.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.4, 0.15.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
abort() was called at PC 0x4008f49c on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x4008a7b8:0x3ffb7710 0x4008ab15:0x3ffb7730 0x4008f49c:0x3ffb7750 0x4008f9b4:0x3ffb7770 0x4008600d:0x3ffb7790 0x4008603e:0x3ffb77b0 0x4008645d:0x3ffb77d0 0x4000beaf:0x3ffb77f0 0x40084081:0x3ffb7810 0x4018a2b1:0x3ffb7830 0x401a1ce9:0x3ffb7850 0x4019cf91:0x3ffb7870 0x4014dc73:0x3ffb7890 0x4014dcdb:0x3ffb78b0 0x4008c55e:0x3ffb78d0

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Ada
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by willmmiles**
Attempt to allocate enough room for the "minimum" sparks; and ensure that we never overrun the allocated array size.

Fixes #4120

### CODE REVIEW

**Review by DedeHai — APPROVED** [review]

File: wled00/FX.cpp [hunk 1]
```diff
@@ -3547,7 +3547,7 @@ uint16_t mode_exploding_fireworks(void)
   if (segs <= (strip.getMaxSegments() /4)) maxData *= 2; //ESP8266: 1024 if <= 4 segs ESP32: 2560 if <= 8 segs
   int maxSparks = maxData / sizeof(spark); //ESP8266: max. 21/42/85 sparks/seg, ESP32: max. 53/106/213 sparks/seg
 
-  unsigned numSparks = min(2 + ((rows*cols) >> 1), maxSparks);
+  unsigned numSparks = min(5 + ((rows*cols) >> 1), maxSparks);
```
Comment (blazoncek) [inline wled00/FX.cpp:3550]: This change alone would be sufficient IMO. It will guarantee that minimum size is 5

Comment (willmmiles) [reply wled00/FX.cpp:3550]: True. I do prefer to be absolutely explicit at the point of usage as well, though - it's saved me a couple times as I don't always remember the subtle relationships between static constants in future refactors.
